export enum NotificationType {
  WELCOME = 1,
  ADD_FIRST_FRIEND = 2,

  CONTACT_REQUEST = 10,

  REFERENCE_INVITE = 20,
  REFERENCE_VIEW_REQUEST = 21,

  STAFF_INVITE = 30,
  STAFF_INVITE_ACCEPTED = 31,

  COMPANY_JOIN_REQUEST = 40,
  COMPANY_JOIN_REQUEST_ACCEPTED = 41,

  APPLICATION_NEW = 50,

  INTERVIEW_NEW = 60,

  OFFER_NEW = 70,

  SUB_NONE = 80,
  SUB_EXPIRED = 81,
  SUB_EXPIRED_SOON = 82,
}